# Minimal ubuntu VM
os: linux
dist: bionic
language: python
python: 3.8

# Docker used in every job
services:
  - docker

# Make docker image creation the first stage
stages:
  - image
  - test
  - deploy

# Use matrix expansion to create package jobs
env:
  - PACKAGE=atlauncher-git
  - PACKAGE=pdlist-git
  - PACKAGE=python-clicolor
  - PACKAGE=python-dnsdumpster-api-git
  - PACKAGE=python-od
  - PACKAGE=python-setuptools-git-ver
  - PACKAGE=seclists-c

# Install python dependencies
install: pip install aur clicolor requests python-dateutil pyyaml schema

# test stage script
script: ./.travis/test_package.sh

# Other jobs
jobs:
  include:
    # Build docker image for other jobs
    - stage: image
      # Don't build if pull request. Docker credentials won't be available
      if: type != pull_request
      script: ./.travis/build_image.sh
      env:
    # Delete old docker images
    - stage: image
      install: pip install requests python-dateutil
      script: python ./.travis/delete_old.py
      services:
      env:
