# Minimal ubuntu VM
os: linux
dist: bionic
language: rust

# Docker used in every job
services:
  - docker

# Make docker image creation the first stage
stages:
  - image
  - test
  - deploy

# Use matrix expansion to create package jobs
env:
  - PACKAGE=atlauncher-git
  - PACKAGE=python-clicolor
  - PACKAGE=seclists-c SKIP_MAKEPKG=
  - PACKAGE=ffuf-bin

# test stage script
script: ./.travis/test_package.sh

# Other jobs
jobs:
  include:
    # Build docker image for other jobs
    - stage: image
      # Don't build if pull request. Docker credentials won't be available
      if: type != pull_request
      script: ./.travis/build_image.sh
      env:
    # Delete old docker images
    - stage: image
      language: python
      install: pip install requests python-dateutil
      script: python ./.travis/delete_old.py
      services:
      env:
