# Minimal ubuntu VM
os: linux
dist: bionic
language: minimal

# Docker used in every job
services:
  - docker

# Make docker image creation the first stage
stages:
  - image
  - test
  - deploy

# Use matrix expansion to create package jobs
env:
  - PACKAGE=atlauncher-git
  - PACKAGE=pdlist-git
  - PACKAGE=python-clicolor
  - PACKAGE=python-clicolor-git
  - PACKAGE=python-dnsdumpster-api-git
  - PACKAGE=python-od
  - PACKAGE=python-setuptools-git-ver

# test stage script
script: ./.travis/test_package.sh

# Other jobs
jobs:
  include:
    # Build docker image for other jobs
    - stage: image
      script: ./.travis/build_docker.sh
      env:
    # Delete old docker images
    - stage: image
      language: python
      python: 3.7
      install: pip install requests python-dateutil
      script: python ./.travis/delete_old.py
      services:
      env:
    - stage: deploy
      language: python
      python: 3.7
      script: echo "TODO"
      services:
      env:
